// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ETHMSGJETSONRTVC50_TAUV_FB_H_
#define FLATBUFFERS_GENERATED_ETHMSGJETSONRTVC50_TAUV_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace TAUV_FB {

struct Eth50HzTxMsg;
struct Eth50HzTxMsgBuilder;

struct ThrusterCommand;
struct ThrusterCommandBuilder;

struct Eth50HzTxMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Eth50HzTxMsgBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_THRUSTER_COMMAND = 4
  };
  const TAUV_FB::ThrusterCommand *thruster_command() const {
    return GetPointer<const TAUV_FB::ThrusterCommand *>(VT_THRUSTER_COMMAND);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_THRUSTER_COMMAND) &&
           verifier.VerifyTable(thruster_command()) &&
           verifier.EndTable();
  }
};

struct Eth50HzTxMsgBuilder {
  typedef Eth50HzTxMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_thruster_command(::flatbuffers::Offset<TAUV_FB::ThrusterCommand> thruster_command) {
    fbb_.AddOffset(Eth50HzTxMsg::VT_THRUSTER_COMMAND, thruster_command);
  }
  explicit Eth50HzTxMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Eth50HzTxMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Eth50HzTxMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Eth50HzTxMsg> CreateEth50HzTxMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<TAUV_FB::ThrusterCommand> thruster_command = 0) {
  Eth50HzTxMsgBuilder builder_(_fbb);
  builder_.add_thruster_command(thruster_command);
  return builder_.Finish();
}

struct Eth50HzTxMsg::Traits {
  using type = Eth50HzTxMsg;
  static auto constexpr Create = CreateEth50HzTxMsg;
};

struct ThrusterCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ThrusterCommandBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RPM = 4,
    VT_ENABLED = 6
  };
  const ::flatbuffers::Vector<int32_t> *rpm() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_RPM);
  }
  const ::flatbuffers::Vector<uint8_t> *enabled() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_ENABLED);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RPM) &&
           verifier.VerifyVector(rpm()) &&
           VerifyOffset(verifier, VT_ENABLED) &&
           verifier.VerifyVector(enabled()) &&
           verifier.EndTable();
  }
};

struct ThrusterCommandBuilder {
  typedef ThrusterCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rpm(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> rpm) {
    fbb_.AddOffset(ThrusterCommand::VT_RPM, rpm);
  }
  void add_enabled(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> enabled) {
    fbb_.AddOffset(ThrusterCommand::VT_ENABLED, enabled);
  }
  explicit ThrusterCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ThrusterCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ThrusterCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ThrusterCommand> CreateThrusterCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> rpm = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> enabled = 0) {
  ThrusterCommandBuilder builder_(_fbb);
  builder_.add_enabled(enabled);
  builder_.add_rpm(rpm);
  return builder_.Finish();
}

struct ThrusterCommand::Traits {
  using type = ThrusterCommand;
  static auto constexpr Create = CreateThrusterCommand;
};

inline ::flatbuffers::Offset<ThrusterCommand> CreateThrusterCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *rpm = nullptr,
    const std::vector<uint8_t> *enabled = nullptr) {
  auto rpm__ = rpm ? _fbb.CreateVector<int32_t>(*rpm) : 0;
  auto enabled__ = enabled ? _fbb.CreateVector<uint8_t>(*enabled) : 0;
  return TAUV_FB::CreateThrusterCommand(
      _fbb,
      rpm__,
      enabled__);
}

inline const TAUV_FB::Eth50HzTxMsg *GetEth50HzTxMsg(const void *buf) {
  return ::flatbuffers::GetRoot<TAUV_FB::Eth50HzTxMsg>(buf);
}

inline const TAUV_FB::Eth50HzTxMsg *GetSizePrefixedEth50HzTxMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<TAUV_FB::Eth50HzTxMsg>(buf);
}

inline bool VerifyEth50HzTxMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<TAUV_FB::Eth50HzTxMsg>(nullptr);
}

inline bool VerifySizePrefixedEth50HzTxMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<TAUV_FB::Eth50HzTxMsg>(nullptr);
}

inline void FinishEth50HzTxMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<TAUV_FB::Eth50HzTxMsg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEth50HzTxMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<TAUV_FB::Eth50HzTxMsg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace TAUV_FB

#endif  // FLATBUFFERS_GENERATED_ETHMSGJETSONRTVC50_TAUV_FB_H_
