// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ETHMSGRTVCJETSON100_TAUV_FB_H_
#define FLATBUFFERS_GENERATED_ETHMSGRTVCJETSON100_TAUV_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace TAUV_FB {

struct Vec3;

struct Quat;

struct Eth100HzMsg;
struct Eth100HzMsgBuilder;

struct XsensIMUFrame;
struct XsensIMUFrameBuilder;

struct DepthSensorFrame;
struct DepthSensorFrameBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  struct Traits;
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Vec3::Traits {
  using type = Vec3;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Quat FLATBUFFERS_FINAL_CLASS {
 private:
  float w_;
  float x_;
  float y_;
  float z_;

 public:
  struct Traits;
  Quat()
      : w_(0),
        x_(0),
        y_(0),
        z_(0) {
  }
  Quat(float _w, float _x, float _y, float _z)
      : w_(::flatbuffers::EndianScalar(_w)),
        x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Quat, 16);

struct Quat::Traits {
  using type = Quat;
};

struct Eth100HzMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Eth100HzMsgBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IMU_DATA = 4,
    VT_DEPTH_DATA = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::XsensIMUFrame>> *imu_data() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::XsensIMUFrame>> *>(VT_IMU_DATA);
  }
  const TAUV_FB::DepthSensorFrame *depth_data() const {
    return GetPointer<const TAUV_FB::DepthSensorFrame *>(VT_DEPTH_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_IMU_DATA) &&
           verifier.VerifyVector(imu_data()) &&
           verifier.VerifyVectorOfTables(imu_data()) &&
           VerifyOffset(verifier, VT_DEPTH_DATA) &&
           verifier.VerifyTable(depth_data()) &&
           verifier.EndTable();
  }
};

struct Eth100HzMsgBuilder {
  typedef Eth100HzMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_imu_data(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::XsensIMUFrame>>> imu_data) {
    fbb_.AddOffset(Eth100HzMsg::VT_IMU_DATA, imu_data);
  }
  void add_depth_data(::flatbuffers::Offset<TAUV_FB::DepthSensorFrame> depth_data) {
    fbb_.AddOffset(Eth100HzMsg::VT_DEPTH_DATA, depth_data);
  }
  explicit Eth100HzMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Eth100HzMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Eth100HzMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Eth100HzMsg> CreateEth100HzMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::XsensIMUFrame>>> imu_data = 0,
    ::flatbuffers::Offset<TAUV_FB::DepthSensorFrame> depth_data = 0) {
  Eth100HzMsgBuilder builder_(_fbb);
  builder_.add_depth_data(depth_data);
  builder_.add_imu_data(imu_data);
  return builder_.Finish();
}

struct Eth100HzMsg::Traits {
  using type = Eth100HzMsg;
  static auto constexpr Create = CreateEth100HzMsg;
};

inline ::flatbuffers::Offset<Eth100HzMsg> CreateEth100HzMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<TAUV_FB::XsensIMUFrame>> *imu_data = nullptr,
    ::flatbuffers::Offset<TAUV_FB::DepthSensorFrame> depth_data = 0) {
  auto imu_data__ = imu_data ? _fbb.CreateVector<::flatbuffers::Offset<TAUV_FB::XsensIMUFrame>>(*imu_data) : 0;
  return TAUV_FB::CreateEth100HzMsg(
      _fbb,
      imu_data__,
      depth_data);
}

struct XsensIMUFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef XsensIMUFrameBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SAMPLE_TIME_FINE = 4,
    VT_PACKET_COUNTER = 6,
    VT_ORIENTATION = 8,
    VT_RATE_OF_TURN = 10,
    VT_FREE_ACCELERATION = 12,
    VT_PRESSURE = 14,
    VT_TEMPERATURE = 16
  };
  uint32_t sample_time_fine() const {
    return GetField<uint32_t>(VT_SAMPLE_TIME_FINE, 0);
  }
  uint32_t packet_counter() const {
    return GetField<uint32_t>(VT_PACKET_COUNTER, 0);
  }
  const TAUV_FB::Quat *orientation() const {
    return GetStruct<const TAUV_FB::Quat *>(VT_ORIENTATION);
  }
  const TAUV_FB::Vec3 *rate_of_turn() const {
    return GetStruct<const TAUV_FB::Vec3 *>(VT_RATE_OF_TURN);
  }
  const TAUV_FB::Vec3 *free_acceleration() const {
    return GetStruct<const TAUV_FB::Vec3 *>(VT_FREE_ACCELERATION);
  }
  float pressure() const {
    return GetField<float>(VT_PRESSURE, 0.0f);
  }
  float temperature() const {
    return GetField<float>(VT_TEMPERATURE, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SAMPLE_TIME_FINE, 4) &&
           VerifyField<uint32_t>(verifier, VT_PACKET_COUNTER, 4) &&
           VerifyField<TAUV_FB::Quat>(verifier, VT_ORIENTATION, 4) &&
           VerifyField<TAUV_FB::Vec3>(verifier, VT_RATE_OF_TURN, 4) &&
           VerifyField<TAUV_FB::Vec3>(verifier, VT_FREE_ACCELERATION, 4) &&
           VerifyField<float>(verifier, VT_PRESSURE, 4) &&
           VerifyField<float>(verifier, VT_TEMPERATURE, 4) &&
           verifier.EndTable();
  }
};

struct XsensIMUFrameBuilder {
  typedef XsensIMUFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sample_time_fine(uint32_t sample_time_fine) {
    fbb_.AddElement<uint32_t>(XsensIMUFrame::VT_SAMPLE_TIME_FINE, sample_time_fine, 0);
  }
  void add_packet_counter(uint32_t packet_counter) {
    fbb_.AddElement<uint32_t>(XsensIMUFrame::VT_PACKET_COUNTER, packet_counter, 0);
  }
  void add_orientation(const TAUV_FB::Quat *orientation) {
    fbb_.AddStruct(XsensIMUFrame::VT_ORIENTATION, orientation);
  }
  void add_rate_of_turn(const TAUV_FB::Vec3 *rate_of_turn) {
    fbb_.AddStruct(XsensIMUFrame::VT_RATE_OF_TURN, rate_of_turn);
  }
  void add_free_acceleration(const TAUV_FB::Vec3 *free_acceleration) {
    fbb_.AddStruct(XsensIMUFrame::VT_FREE_ACCELERATION, free_acceleration);
  }
  void add_pressure(float pressure) {
    fbb_.AddElement<float>(XsensIMUFrame::VT_PRESSURE, pressure, 0.0f);
  }
  void add_temperature(float temperature) {
    fbb_.AddElement<float>(XsensIMUFrame::VT_TEMPERATURE, temperature, 0.0f);
  }
  explicit XsensIMUFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<XsensIMUFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<XsensIMUFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<XsensIMUFrame> CreateXsensIMUFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sample_time_fine = 0,
    uint32_t packet_counter = 0,
    const TAUV_FB::Quat *orientation = nullptr,
    const TAUV_FB::Vec3 *rate_of_turn = nullptr,
    const TAUV_FB::Vec3 *free_acceleration = nullptr,
    float pressure = 0.0f,
    float temperature = 0.0f) {
  XsensIMUFrameBuilder builder_(_fbb);
  builder_.add_temperature(temperature);
  builder_.add_pressure(pressure);
  builder_.add_free_acceleration(free_acceleration);
  builder_.add_rate_of_turn(rate_of_turn);
  builder_.add_orientation(orientation);
  builder_.add_packet_counter(packet_counter);
  builder_.add_sample_time_fine(sample_time_fine);
  return builder_.Finish();
}

struct XsensIMUFrame::Traits {
  using type = XsensIMUFrame;
  static auto constexpr Create = CreateXsensIMUFrame;
};

struct DepthSensorFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DepthSensorFrameBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PRESSURE = 4,
    VT_DEPTH = 6,
    VT_TEMPERATURE = 8
  };
  float pressure() const {
    return GetField<float>(VT_PRESSURE, 0.0f);
  }
  float depth() const {
    return GetField<float>(VT_DEPTH, 0.0f);
  }
  float temperature() const {
    return GetField<float>(VT_TEMPERATURE, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_PRESSURE, 4) &&
           VerifyField<float>(verifier, VT_DEPTH, 4) &&
           VerifyField<float>(verifier, VT_TEMPERATURE, 4) &&
           verifier.EndTable();
  }
};

struct DepthSensorFrameBuilder {
  typedef DepthSensorFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pressure(float pressure) {
    fbb_.AddElement<float>(DepthSensorFrame::VT_PRESSURE, pressure, 0.0f);
  }
  void add_depth(float depth) {
    fbb_.AddElement<float>(DepthSensorFrame::VT_DEPTH, depth, 0.0f);
  }
  void add_temperature(float temperature) {
    fbb_.AddElement<float>(DepthSensorFrame::VT_TEMPERATURE, temperature, 0.0f);
  }
  explicit DepthSensorFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DepthSensorFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DepthSensorFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DepthSensorFrame> CreateDepthSensorFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float pressure = 0.0f,
    float depth = 0.0f,
    float temperature = 0.0f) {
  DepthSensorFrameBuilder builder_(_fbb);
  builder_.add_temperature(temperature);
  builder_.add_depth(depth);
  builder_.add_pressure(pressure);
  return builder_.Finish();
}

struct DepthSensorFrame::Traits {
  using type = DepthSensorFrame;
  static auto constexpr Create = CreateDepthSensorFrame;
};

inline const TAUV_FB::Eth100HzMsg *GetEth100HzMsg(const void *buf) {
  return ::flatbuffers::GetRoot<TAUV_FB::Eth100HzMsg>(buf);
}

inline const TAUV_FB::Eth100HzMsg *GetSizePrefixedEth100HzMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<TAUV_FB::Eth100HzMsg>(buf);
}

inline bool VerifyEth100HzMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<TAUV_FB::Eth100HzMsg>(nullptr);
}

inline bool VerifySizePrefixedEth100HzMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<TAUV_FB::Eth100HzMsg>(nullptr);
}

inline void FinishEth100HzMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<TAUV_FB::Eth100HzMsg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEth100HzMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<TAUV_FB::Eth100HzMsg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace TAUV_FB

#endif  // FLATBUFFERS_GENERATED_ETHMSGRTVCJETSON100_TAUV_FB_H_
