// Generated by gencpp from file uuv_gazebo_ros_plugins_msgs/GetListParam.msg
// DO NOT EDIT!


#ifndef UUV_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETLISTPARAM_H
#define UUV_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETLISTPARAM_H

#include <ros/service_traits.h>


#include <uuv_gazebo_ros_plugins_msgs/GetListParamRequest.h>
#include <uuv_gazebo_ros_plugins_msgs/GetListParamResponse.h>


namespace uuv_gazebo_ros_plugins_msgs
{

struct GetListParam
{

typedef GetListParamRequest Request;
typedef GetListParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetListParam
} // namespace uuv_gazebo_ros_plugins_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParam > {
  static const char* value()
  {
    return "d3415e6ab074fdc7b0bd82ed3d6fccc7";
  }

  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetListParam&) { return value(); }
};

template<>
struct DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParam > {
  static const char* value()
  {
    return "uuv_gazebo_ros_plugins_msgs/GetListParam";
  }

  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetListParam&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParamRequest> should match
// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParam >
template<>
struct MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParam >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetListParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParamRequest> should match
// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParam >
template<>
struct DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParamRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParam >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetListParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParamResponse> should match
// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParam >
template<>
struct MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetListParam >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetListParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParamResponse> should match
// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParam >
template<>
struct DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParamResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_gazebo_ros_plugins_msgs::GetListParam >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetListParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETLISTPARAM_H
