repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
        args: [-i]
        files: \.(c|cpp|h|hpp)$

  - repo: https://github.com/pocc/pre-commit-cppcheck
    rev: v0.0.1
    hooks:
      - id: cppcheck
        args: [--enable=all, --inconclusive, --std=c99, --quiet]