line-length = 100
indent-width = 4
target-version = "py312"

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]
ignore = []

[format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[lint.isort]
combine-as-imports = true

[lint.per-file-ignores]
# No checks in firmware/
"firmware/**" = ["ALL"]
