mesh_downsampling:
  default_max_faces: 1000
  per_mesh_limits:
    os_hull.stl:
      max_faces: 5000
    os_launcher.stl:
      max_faces: 5000
    thruster.stl:
      max_faces: 600
onshape:
  access_key: bVFHkb2TggcI3ySynCGN9CsM
  api_url: https://cad.onshape.com
  secret_key: 3wqwvTFwaR2XyF2PeWzXudSu2nKb3ljOGq2vcrh35AkwE7jK
output:
  overwrite_existing: true
  scenario_file: osprey.scn
