name: osprey
# base_link_mass_override: 23.0
material: Aluminium
look: Red
thruster_setpoint_topic: sim/thruster_setpoint
servo_setpoint_topic: sim/servo_setpoint
thruster_state_topic: sim/thruster_state
include_arm: false
sensors:
  imu:
    type: imu
    rate: 100.0
    parameters:
      angular_velocity_range: 7.85 7.85 7.85
      linear_acceleration_range: '20.0'
      angle_noise: 0.0 0.0 0.0
      angular_velocity_noise: '0.00175'
      yaw_drift: '0.0'
      linear_acceleration_noise: '0.00589'
      ros_topic: vehicle/sensors/imu
  dvl:
    type: dvl
    rate: 7.0
    parameters:
      beam_angle: '22.5'
      beam_positive_z: 'true'
      velocity_range: 10.0 10.0 5.0
      altitude_min: '0.05'
      altitude_max: '50.0'
      minimum_layer_size: '10.0'
      boundary_near: '10.0'
      boundary_far: '30.0'
      velocity_percent_noise: '0.1'
      velocity_noise: '0.01'
      altitude_noise: '0.01'
      water_velocity_percent_noise: '0.1'
      water_velocity_noise: '0.1'
      history_samples: '1'
      ros_topic: sim/dvl
  pressure:
    type: pressure
    rate: 100.0
    parameters:
      pressure_range: '3000000.0'
      pressure_noise: '0.1'
      history_samples: '1'
      ros_topic: sim/pressure
thruster:
  max_setpoint: 362.9 # rad/s
  inverted_setpoint: false
  normalized_setpoint: false
  propeller_diameter: 0.2
  propeller_right: true
  propeller_mesh: t200_prop_ccw.obj
  thrust_coeff_forward: 3.645e-3 # N/(rad/s)^2
  thrust_coeff_reverse: 2.905e-3 # N/(rad/s)^2
  deadband_lower: -40.63 # rad/s
  deadband_upper: 32.25  # rad/s
