(cl:defpackage tauv_msgs-srv
  (:use )
  (:export
   "GETTRAJ"
   "<GETTRAJ-REQUEST>"
   "GETTRAJ-REQUEST"
   "<GETTRAJ-RESPONSE>"
   "GETTRAJ-RESPONSE"
   "TUNEINERTIAL"
   "<TUNEINERTIAL-REQUEST>"
   "TUNEINERTIAL-REQUEST"
   "<TUNEINERTIAL-RESPONSE>"
   "TUNEINERTIAL-RESPONSE"
   "TUNEPID"
   "<TUNEPID-REQUEST>"
   "TUNEPID-REQUEST"
   "<TUNEPID-RESPONSE>"
   "TUNEPID-RESPONSE"
  ))

