// Generated by gencpp from file tauv_msgs/GetTraj.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_GETTRAJ_H
#define TAUV_MSGS_MESSAGE_GETTRAJ_H

#include <ros/service_traits.h>


#include <tauv_msgs/GetTrajRequest.h>
#include <tauv_msgs/GetTrajResponse.h>


namespace tauv_msgs
{

struct GetTraj
{

typedef GetTrajRequest Request;
typedef GetTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTraj
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::GetTraj > {
  static const char* value()
  {
    return "e104c1c4c7e7c1d03d3c9b5d5780f143";
  }

  static const char* value(const ::tauv_msgs::GetTraj&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::GetTraj > {
  static const char* value()
  {
    return "tauv_msgs/GetTraj";
  }

  static const char* value(const ::tauv_msgs::GetTraj&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::GetTrajRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::GetTraj >
template<>
struct MD5Sum< ::tauv_msgs::GetTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::GetTraj >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::GetTrajRequest> should match
// service_traits::DataType< ::tauv_msgs::GetTraj >
template<>
struct DataType< ::tauv_msgs::GetTrajRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::GetTraj >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::GetTrajResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::GetTraj >
template<>
struct MD5Sum< ::tauv_msgs::GetTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::GetTraj >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::GetTrajResponse> should match
// service_traits::DataType< ::tauv_msgs::GetTraj >
template<>
struct DataType< ::tauv_msgs::GetTrajResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::GetTraj >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_GETTRAJ_H
