// Generated by gencpp from file tauv_msgs/PoseGraphMeasurement.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_POSEGRAPHMEASUREMENT_H
#define TAUV_MSGS_MESSAGE_POSEGRAPHMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct PoseGraphMeasurement_
{
  typedef PoseGraphMeasurement_<ContainerAllocator> Type;

  PoseGraphMeasurement_()
    : header()
    , landmark_id(0)
    , position()  {
    }
  PoseGraphMeasurement_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , landmark_id(0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _landmark_id_type;
  _landmark_id_type landmark_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct PoseGraphMeasurement_

typedef ::tauv_msgs::PoseGraphMeasurement_<std::allocator<void> > PoseGraphMeasurement;

typedef boost::shared_ptr< ::tauv_msgs::PoseGraphMeasurement > PoseGraphMeasurementPtr;
typedef boost::shared_ptr< ::tauv_msgs::PoseGraphMeasurement const> PoseGraphMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator1> & lhs, const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.landmark_id == rhs.landmark_id &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator1> & lhs, const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e27f94f75bfdd40c9e3cb1c46d27f36";
  }

  static const char* value(const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e27f94f75bfdd40ULL;
  static const uint64_t static_value2 = 0xc9e3cb1c46d27f36ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/PoseGraphMeasurement";
  }

  static const char* value(const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 landmark_id\n"
"geometry_msgs/Point position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.landmark_id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseGraphMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::PoseGraphMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "landmark_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.landmark_id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_POSEGRAPHMEASUREMENT_H
