// Generated by gencpp from file tauv_msgs/TuneInertial.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_TUNEINERTIAL_H
#define TAUV_MSGS_MESSAGE_TUNEINERTIAL_H

#include <ros/service_traits.h>


#include <tauv_msgs/TuneInertialRequest.h>
#include <tauv_msgs/TuneInertialResponse.h>


namespace tauv_msgs
{

struct TuneInertial
{

typedef TuneInertialRequest Request;
typedef TuneInertialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TuneInertial
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::TuneInertial > {
  static const char* value()
  {
    return "b07a11376c5b2ae9ec7888a1a74564d4";
  }

  static const char* value(const ::tauv_msgs::TuneInertial&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::TuneInertial > {
  static const char* value()
  {
    return "tauv_msgs/TuneInertial";
  }

  static const char* value(const ::tauv_msgs::TuneInertial&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::TuneInertialRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::TuneInertial >
template<>
struct MD5Sum< ::tauv_msgs::TuneInertialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::TuneInertial >::value();
  }
  static const char* value(const ::tauv_msgs::TuneInertialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::TuneInertialRequest> should match
// service_traits::DataType< ::tauv_msgs::TuneInertial >
template<>
struct DataType< ::tauv_msgs::TuneInertialRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::TuneInertial >::value();
  }
  static const char* value(const ::tauv_msgs::TuneInertialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::TuneInertialResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::TuneInertial >
template<>
struct MD5Sum< ::tauv_msgs::TuneInertialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::TuneInertial >::value();
  }
  static const char* value(const ::tauv_msgs::TuneInertialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::TuneInertialResponse> should match
// service_traits::DataType< ::tauv_msgs::TuneInertial >
template<>
struct DataType< ::tauv_msgs::TuneInertialResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::TuneInertial >::value();
  }
  static const char* value(const ::tauv_msgs::TuneInertialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_TUNEINERTIAL_H
