version: '3.4'

services:
  tauv-desktop:
    image: ghcr.io/tartan-auv/desktop_nogpu_user:latest
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined   
    volumes:
      - ../:/tauv-mono
    devices:
      - /dev:/dev
    command: /bin/sh -c "while sleep 1000; do :; done"
