services:
  osprey-dev:
    image: tartanauv/osprey-dev:latest
    network_mode: host
    stdin_open: true
    tty: true
    container_name: osprey-dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
    runtime: nvidia
    volumes:
      - /home/tauv/tauv-mono/ros_ws:/ros_ws

  desktop-dev:
    image: tartanauv/desktop-dev:latest
    network_mode: host
    stdin_open: true
    tty: true
    container_name: desktop-dev
    volumes:
      - ../packages:/ros_ws/src/tauv-packages
      - ../ros_artifacts/logs:/ros_ws/logs
      - ../ros_artifacts/build:/ros_ws/build
  