version: '3.4'

services:
  tauv-desktop:
    image: ghcr.io/tartan-auv/desktop_nogpu_user:latest
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined   
    volumes:
      - ../:/tauv-mono
      - ${SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/ssh-agent
      - /tmp/X11-unix:/tmp/X11-unix:ro
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - DISPLAY=:0
    devices:
      - /dev:/dev
    command: /bin/sh -c "while sleep 1000; do :; done"

  osprey-orin-user:
    image: ghcr.io/tartan-auv/osprey_orin_user:latest
    network_mode: "host"
    privileged: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev:/dev
    volumes:
      - /home/tauv/tauv-mono:/tauv-mono
      - /home/tauv/data:/data
    command: /bin/sh -c "while sleep 1000; do :; done"
