services:
  osprey-orin-dev:
    image: tartanauv/tauv-orin-base:r36.4.3
    network_mode: host
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
    container_name: tauv_gen_2_container