// Generated by gencpp from file uuv_world_ros_plugins_msgs/GetOriginSphericalCoordResponse.msg
// DO NOT EDIT!


#ifndef UUV_WORLD_ROS_PLUGINS_MSGS_MESSAGE_GETORIGINSPHERICALCOORDRESPONSE_H
#define UUV_WORLD_ROS_PLUGINS_MSGS_MESSAGE_GETORIGINSPHERICALCOORDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uuv_world_ros_plugins_msgs
{
template <class ContainerAllocator>
struct GetOriginSphericalCoordResponse_
{
  typedef GetOriginSphericalCoordResponse_<ContainerAllocator> Type;

  GetOriginSphericalCoordResponse_()
    : latitude_deg(0.0)
    , longitude_deg(0.0)
    , altitude(0.0)  {
    }
  GetOriginSphericalCoordResponse_(const ContainerAllocator& _alloc)
    : latitude_deg(0.0)
    , longitude_deg(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_deg_type;
  _latitude_deg_type latitude_deg;

   typedef double _longitude_deg_type;
  _longitude_deg_type longitude_deg;

   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetOriginSphericalCoordResponse_

typedef ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<std::allocator<void> > GetOriginSphericalCoordResponse;

typedef boost::shared_ptr< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse > GetOriginSphericalCoordResponsePtr;
typedef boost::shared_ptr< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse const> GetOriginSphericalCoordResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator1> & lhs, const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator2> & rhs)
{
  return lhs.latitude_deg == rhs.latitude_deg &&
    lhs.longitude_deg == rhs.longitude_deg &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator1> & lhs, const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_world_ros_plugins_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60457d630fe21cc5f8f6bd5d0fc90156";
  }

  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60457d630fe21cc5ULL;
  static const uint64_t static_value2 = 0xf8f6bd5d0fc90156ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_world_ros_plugins_msgs/GetOriginSphericalCoordResponse";
  }

  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Latitude [degrees]. Positive is north of equator; negative is south.\n"
"float64 latitude_deg\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is west.\n"
"float64 longitude_deg\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid\n"
"float64 altitude\n"
"\n"
;
  }

  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude_deg);
      stream.next(m.longitude_deg);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetOriginSphericalCoordResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse_<ContainerAllocator>& v)
  {
    s << indent << "latitude_deg: ";
    Printer<double>::stream(s, indent + "  ", v.latitude_deg);
    s << indent << "longitude_deg: ";
    Printer<double>::stream(s, indent + "  ", v.longitude_deg);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_WORLD_ROS_PLUGINS_MSGS_MESSAGE_GETORIGINSPHERICALCOORDRESPONSE_H
