# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/ControllerCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControllerCmd(genpy.Message):
  _md5sum = "c0612f34c73db057150c241e2726f1e9"
  _type = "tauv_msgs/ControllerCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 a_x  # Acceleration in fixed frame x direction
float32 a_y  # Acceleration in fixed frame y direction
float32 a_z  # Acceleration in fixed frame z direction
float32 a_yaw  # Acceleration in fixed frame yaw direction
float32 p_roll  # roll target
float32 p_pitch  # pitch target"""
  __slots__ = ['a_x','a_y','a_z','a_yaw','p_roll','p_pitch']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a_x,a_y,a_z,a_yaw,p_roll,p_pitch

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControllerCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.a_x is None:
        self.a_x = 0.
      if self.a_y is None:
        self.a_y = 0.
      if self.a_z is None:
        self.a_z = 0.
      if self.a_yaw is None:
        self.a_yaw = 0.
      if self.p_roll is None:
        self.p_roll = 0.
      if self.p_pitch is None:
        self.p_pitch = 0.
    else:
      self.a_x = 0.
      self.a_y = 0.
      self.a_z = 0.
      self.a_yaw = 0.
      self.p_roll = 0.
      self.p_pitch = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.a_x, _x.a_y, _x.a_z, _x.a_yaw, _x.p_roll, _x.p_pitch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.a_x, _x.a_y, _x.a_z, _x.a_yaw, _x.p_roll, _x.p_pitch,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.a_x, _x.a_y, _x.a_z, _x.a_yaw, _x.p_roll, _x.p_pitch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.a_x, _x.a_y, _x.a_z, _x.a_yaw, _x.p_roll, _x.p_pitch,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
