# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/InertialVals.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class InertialVals(genpy.Message):
  _md5sum = "dc905a6a26bfe30465ae55cdfc3db94e"
  _type = "tauv_msgs/InertialVals"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 mass
float32 buoyancy
float32 ixx
float32 iyy
float32 izz"""
  __slots__ = ['mass','buoyancy','ixx','iyy','izz']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mass,buoyancy,ixx,iyy,izz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InertialVals, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mass is None:
        self.mass = 0.
      if self.buoyancy is None:
        self.buoyancy = 0.
      if self.ixx is None:
        self.ixx = 0.
      if self.iyy is None:
        self.iyy = 0.
      if self.izz is None:
        self.izz = 0.
    else:
      self.mass = 0.
      self.buoyancy = 0.
      self.ixx = 0.
      self.iyy = 0.
      self.izz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.mass, _x.buoyancy, _x.ixx, _x.iyy, _x.izz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.mass, _x.buoyancy, _x.ixx, _x.iyy, _x.izz,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.mass, _x.buoyancy, _x.ixx, _x.iyy, _x.izz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.mass, _x.buoyancy, _x.ixx, _x.iyy, _x.izz,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
