# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/PidVals.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PidVals(genpy.Message):
  _md5sum = "d4db47770a0caf47edbb925bd3a9269a"
  _type = "tauv_msgs/PidVals"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 a_p
float32 a_i
float32 a_d
float32 a_sat
float32 l_p
float32 l_i
float32 l_d
float32 l_sat"""
  __slots__ = ['a_p','a_i','a_d','a_sat','l_p','l_i','l_d','l_sat']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a_p,a_i,a_d,a_sat,l_p,l_i,l_d,l_sat

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PidVals, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.a_p is None:
        self.a_p = 0.
      if self.a_i is None:
        self.a_i = 0.
      if self.a_d is None:
        self.a_d = 0.
      if self.a_sat is None:
        self.a_sat = 0.
      if self.l_p is None:
        self.l_p = 0.
      if self.l_i is None:
        self.l_i = 0.
      if self.l_d is None:
        self.l_d = 0.
      if self.l_sat is None:
        self.l_sat = 0.
    else:
      self.a_p = 0.
      self.a_i = 0.
      self.a_d = 0.
      self.a_sat = 0.
      self.l_p = 0.
      self.l_i = 0.
      self.l_d = 0.
      self.l_sat = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.a_p, _x.a_i, _x.a_d, _x.a_sat, _x.l_p, _x.l_i, _x.l_d, _x.l_sat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.a_p, _x.a_i, _x.a_d, _x.a_sat, _x.l_p, _x.l_i, _x.l_d, _x.l_sat,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.a_p, _x.a_i, _x.a_d, _x.a_sat, _x.l_p, _x.l_i, _x.l_d, _x.l_sat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.a_p, _x.a_i, _x.a_d, _x.a_sat, _x.l_p, _x.l_i, _x.l_d, _x.l_sat,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
