# **THIS IS AN AUTOGENERATED FILE, DO NOT EDIT MANUALLY**
# 
# Generated by generate_alarms.py (Tom Scherlis 2022)
# This file is generated whenever tauv_common is built using catkin build.
# See alarms/CMakeLists.txt for configuring the autogen build step
# 
# Generated on Tue Nov  8 01:06:09 2022

from tauv_alarms.alarm_util import AlarmMeta, AlarmType, FailureLevel

class Alarm(metaclass=AlarmMeta):
    UNKNOWN_ALARMS = AlarmType(
        name="UNKNOWN_ALARMS",
        id=0,
        failure_level=FailureLevel.NO_FAILURE,
        default_set=False,
        description="Special alarm indicating that the client is not connected to the server. Do not set manually.",
        author="Tom Scherlis",
    )
    
    THRUSTERS_NOT_INITIALIZED = AlarmType(
        name="THRUSTERS_NOT_INITIALIZED",
        id=1,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="Thrusters not yet initialized",
        author="Tom Scherlis",
    )
    
    ARDUINO_NOT_INITIALIZED = AlarmType(
        name="ARDUINO_NOT_INITIALIZED",
        id=2,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="Arduino is not initialized yet",
        author="Theo Chemel",
    )
    
    IMU_NOT_INITIALIZED = AlarmType(
        name="IMU_NOT_INITIALIZED",
        id=3,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="IMU is not initialized yet",
        author="Theo Chemel",
    )
    
    IMU_SYNC_NOT_INITIALIZED = AlarmType(
        name="IMU_SYNC_NOT_INITIALIZED",
        id=4,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="IMU sync is not initialized yet",
        author="Theo Chemel",
    )
    
    DVL_NOT_INITIALIZED = AlarmType(
        name="DVL_NOT_INITIALIZED",
        id=5,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="DVL is not initialized yet",
        author="Tom Scherlis",
    )
    
    DVL_NO_TIMESTAMPS = AlarmType(
        name="DVL_NO_TIMESTAMPS",
        id=6,
        failure_level=FailureLevel.NO_FAILURE,
        default_set=False,
        description="DVL has no valid IMU sync timestamps",
        author="Theo Chemel",
    )
    
    DVL_NO_LOCK = AlarmType(
        name="DVL_NO_LOCK",
        id=7,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=False,
        description="DVL has no bottom lock",
        author="Theo Chemel",
    )
    
    SONAR_NOT_INITIALIZED = AlarmType(
        name="SONAR_NOT_INITIALIZED",
        id=8,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=False,
        description="Sonar is not initialized yet",
        author="Theo Chemel",
    )
    
    STATE_ESTIMATION_NOT_INITIALIZED = AlarmType(
        name="STATE_ESTIMATION_NOT_INITIALIZED",
        id=9,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=False,
        description="State estimation is not initialized yet",
        author="Theo Chemel",
    )
    
    STATE_ESTIMATION_DELAYED = AlarmType(
        name="STATE_ESTIMATION_DELAYED",
        id=10,
        failure_level=FailureLevel.NO_FAILURE,
        default_set=False,
        description="State estimation delayed queue is too large",
        author="Theo Chemel",
    )
    
    KILL_SWITCH_ACTIVE = AlarmType(
        name="KILL_SWITCH_ACTIVE",
        id=11,
        failure_level=FailureLevel.CRITICAL_FAILURE,
        default_set=False,
        description="The hardware kill switch is active",
        author="Tom Scherlis",
    )
    
    CONTROLLER_NOT_INITIALIZED = AlarmType(
        name="CONTROLLER_NOT_INITIALIZED",
        id=12,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="Controller is not initialized yet",
        author="Theo Chemel",
    )
    
    MPC_PLANNER_NOT_INITIALIZED = AlarmType(
        name="MPC_PLANNER_NOT_INITIALIZED",
        id=13,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=False,
        description="MPC Planner is not initialized yet",
        author="Theo Chemel",
    )
    
    SUB_DISARMED = AlarmType(
        name="SUB_DISARMED",
        id=14,
        failure_level=FailureLevel.NO_FAILURE,
        default_set=False,
        description="The sub is disarmed",
        author="Tom Scherlis",
    )
    
    CAMERA_NO_VIDEO_FRONT = AlarmType(
        name="CAMERA_NO_VIDEO_FRONT",
        id=15,
        failure_level=FailureLevel.MISSION_FAILURE,
        default_set=True,
        description="No video from camera A (front cam)",
        author="Tom Scherlis",
    )
    
    CAMERA_NO_VIDEO_BOTTOM = AlarmType(
        name="CAMERA_NO_VIDEO_BOTTOM",
        id=16,
        failure_level=FailureLevel.NO_FAILURE,
        default_set=True,
        description="No video from camera B (bottom cam)",
        author="Tom Scherlis",
    )
    
    GNC_NO_POSE = AlarmType(
        name="GNC_NO_POSE",
        id=17,
        failure_level=FailureLevel.MISSION_FAILURE,
        default_set=True,
        description="No pose published from GNC system",
        author="Tom Scherlis",
    )
    
    MISSION_MANAGER_NOT_INITIALIZED = AlarmType(
        name="MISSION_MANAGER_NOT_INITIALIZED",
        id=18,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="Mission manager is not initialized",
        author="Tom Scherlis",
    )
    
    BUCKET_NOT_INITIALIZED = AlarmType(
        name="BUCKET_NOT_INITIALIZED",
        id=19,
        failure_level=FailureLevel.PREDIVE_FAILURE,
        default_set=True,
        description="Bucket system is not yet running",
        author="Katia Nikiforova",
    )
    
    BUCKET_LIST_NOT_PUBLISHING = AlarmType(
        name="BUCKET_LIST_NOT_PUBLISHING",
        id=20,
        failure_level=FailureLevel.NO_FAILURE,
        default_set=True,
        description="Bucket detection list is not actively being published",
        author="Katia Nikiforova",
    )
    
    DARKNET_NOT_PUBLISHING = AlarmType(
        name="DARKNET_NOT_PUBLISHING",
        id=21,
        failure_level=FailureLevel.NO_FAILURE,
        default_set=True,
        description="Darknet isn't running",
        author="Tom Scherlis",
    )
    

