# Goal definition
geometry_msgs/Pose target_pose         # Target pose in odom frame
float32 velocity                       # Desired velocity in m/s
geometry_msgs/Point position_tolerance # Allowed distance away from target_pose position in all axes
float32 angular_tolerance               # Allowed difference in radians between final orientation and orientation in target_pose
---
# Result definition
bool success                    # Whether the goto was completed
string message                  # Status message
---
# Feedback definition
geometry_msgs/Pose current_pose # Current pose in odom frame
float32 distance_remaining      # Distance remaining to target in meters
float32 current_velocity        # Current velocity magnitude in m/s
