#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_response_vis.response_vis import ResponseVis

plugin = 'rqt_response_vis'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
