// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ETHMSGRTVCJETSON50_TAUV_FB_H_
#define FLATBUFFERS_GENERATED_ETHMSGRTVCJETSON50_TAUV_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace TAUV_FB {

struct Eth50HzESCMsg;
struct Eth50HzESCMsgBuilder;

struct ESCFrame;
struct ESCFrameBuilder;

struct Eth50HzESCMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Eth50HzESCMsgBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ESC_DATA = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::ESCFrame>> *esc_data() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::ESCFrame>> *>(VT_ESC_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ESC_DATA) &&
           verifier.VerifyVector(esc_data()) &&
           verifier.VerifyVectorOfTables(esc_data()) &&
           verifier.EndTable();
  }
};

struct Eth50HzESCMsgBuilder {
  typedef Eth50HzESCMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_esc_data(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::ESCFrame>>> esc_data) {
    fbb_.AddOffset(Eth50HzESCMsg::VT_ESC_DATA, esc_data);
  }
  explicit Eth50HzESCMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Eth50HzESCMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Eth50HzESCMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Eth50HzESCMsg> CreateEth50HzESCMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<TAUV_FB::ESCFrame>>> esc_data = 0) {
  Eth50HzESCMsgBuilder builder_(_fbb);
  builder_.add_esc_data(esc_data);
  return builder_.Finish();
}

struct Eth50HzESCMsg::Traits {
  using type = Eth50HzESCMsg;
  static auto constexpr Create = CreateEth50HzESCMsg;
};

inline ::flatbuffers::Offset<Eth50HzESCMsg> CreateEth50HzESCMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<TAUV_FB::ESCFrame>> *esc_data = nullptr) {
  auto esc_data__ = esc_data ? _fbb.CreateVector<::flatbuffers::Offset<TAUV_FB::ESCFrame>>(*esc_data) : 0;
  return TAUV_FB::CreateEth50HzESCMsg(
      _fbb,
      esc_data__);
}

struct ESCFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ESCFrameBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_RPM = 6,
    VT_VOLTAGE = 8,
    VT_CURRENT = 10,
    VT_TEMPERATURE = 12,
    VT_FAULT_CODE = 14
  };
  uint8_t id() const {
    return GetField<uint8_t>(VT_ID, 0);
  }
  int32_t rpm() const {
    return GetField<int32_t>(VT_RPM, 0);
  }
  float voltage() const {
    return GetField<float>(VT_VOLTAGE, 0.0f);
  }
  float current() const {
    return GetField<float>(VT_CURRENT, 0.0f);
  }
  float temperature() const {
    return GetField<float>(VT_TEMPERATURE, 0.0f);
  }
  uint8_t fault_code() const {
    return GetField<uint8_t>(VT_FAULT_CODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ID, 1) &&
           VerifyField<int32_t>(verifier, VT_RPM, 4) &&
           VerifyField<float>(verifier, VT_VOLTAGE, 4) &&
           VerifyField<float>(verifier, VT_CURRENT, 4) &&
           VerifyField<float>(verifier, VT_TEMPERATURE, 4) &&
           VerifyField<uint8_t>(verifier, VT_FAULT_CODE, 1) &&
           verifier.EndTable();
  }
};

struct ESCFrameBuilder {
  typedef ESCFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint8_t id) {
    fbb_.AddElement<uint8_t>(ESCFrame::VT_ID, id, 0);
  }
  void add_rpm(int32_t rpm) {
    fbb_.AddElement<int32_t>(ESCFrame::VT_RPM, rpm, 0);
  }
  void add_voltage(float voltage) {
    fbb_.AddElement<float>(ESCFrame::VT_VOLTAGE, voltage, 0.0f);
  }
  void add_current(float current) {
    fbb_.AddElement<float>(ESCFrame::VT_CURRENT, current, 0.0f);
  }
  void add_temperature(float temperature) {
    fbb_.AddElement<float>(ESCFrame::VT_TEMPERATURE, temperature, 0.0f);
  }
  void add_fault_code(uint8_t fault_code) {
    fbb_.AddElement<uint8_t>(ESCFrame::VT_FAULT_CODE, fault_code, 0);
  }
  explicit ESCFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ESCFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ESCFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ESCFrame> CreateESCFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t id = 0,
    int32_t rpm = 0,
    float voltage = 0.0f,
    float current = 0.0f,
    float temperature = 0.0f,
    uint8_t fault_code = 0) {
  ESCFrameBuilder builder_(_fbb);
  builder_.add_temperature(temperature);
  builder_.add_current(current);
  builder_.add_voltage(voltage);
  builder_.add_rpm(rpm);
  builder_.add_fault_code(fault_code);
  builder_.add_id(id);
  return builder_.Finish();
}

struct ESCFrame::Traits {
  using type = ESCFrame;
  static auto constexpr Create = CreateESCFrame;
};

inline const TAUV_FB::Eth50HzESCMsg *GetEth50HzESCMsg(const void *buf) {
  return ::flatbuffers::GetRoot<TAUV_FB::Eth50HzESCMsg>(buf);
}

inline const TAUV_FB::Eth50HzESCMsg *GetSizePrefixedEth50HzESCMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<TAUV_FB::Eth50HzESCMsg>(buf);
}

inline bool VerifyEth50HzESCMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<TAUV_FB::Eth50HzESCMsg>(nullptr);
}

inline bool VerifySizePrefixedEth50HzESCMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<TAUV_FB::Eth50HzESCMsg>(nullptr);
}

inline void FinishEth50HzESCMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<TAUV_FB::Eth50HzESCMsg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEth50HzESCMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<TAUV_FB::Eth50HzESCMsg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace TAUV_FB

#endif  // FLATBUFFERS_GENERATED_ETHMSGRTVCJETSON50_TAUV_FB_H_
