ARG BASE_IMAGE

FROM ${BASE_IMAGE}

# ROS desktop packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-noetic-desktop-full=1.5.0-1* \
    && rm -rf /var/lib/apt/lists/*

# Misc 
RUN apt-get update && apt-get install -y --no-install-recommends \
    tmux neovim

# Kalibr
RUN apt-get update && apt-get install -y \
    git wget autoconf automake nano \
    libeigen3-dev libboost-all-dev libsuitesparse-dev \
    doxygen libopencv-dev \
    libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
    python3-dev python3-pip python3-scipy \
    python3-matplotlib ipython3 python3-wxgtk4.0 python3-tk python3-igraph python3-pyx

RUN echo 'alias vim="nvim"' >> /root/.bashrc
RUN echo 'chsh -s /bin/bash' >> /root/.bashrc
RUN echo 'source /opt/ros/noetic/setup.bash' >> /root/.bashrc
RUN echo 'source /shared/tauv_ws/devel/setup.bash' >> /root/.bashrc

# ENTYPOINT
COPY apps/surface/entrypoint-workstation.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
