[package]
name = "tauv_gnc"
version = "0.1.0"
edition = "2021"

[[bin]]
name="depth_estimator"
path="src/depth_estimator/depth_estimator.rs"

[[bin]]
name="state_estimator"
path="src/state_estimator/state_estimator.rs"

[dependencies]
rclrs = "*"
std_msgs = "*"
nav_msgs = "*"
sensor_msgs = "*"
geometry_msgs = "*"
tauv_msgs = "*"
std_srvs = "*"
builtin_interfaces = "*"
tf2_msgs = "*"
nalgebra = "*"
approx = "*"
