// Generated by gencpp from file tauv_joy/JoyConnectResponse.msg
// DO NOT EDIT!


#ifndef TAUV_JOY_MESSAGE_JOYCONNECTRESPONSE_H
#define TAUV_JOY_MESSAGE_JOYCONNECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_joy
{
template <class ContainerAllocator>
struct JoyConnectResponse_
{
  typedef JoyConnectResponse_<ContainerAllocator> Type;

  JoyConnectResponse_()
    : success(false)
    , message()  {
    }
  JoyConnectResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JoyConnectResponse_

typedef ::tauv_joy::JoyConnectResponse_<std::allocator<void> > JoyConnectResponse;

typedef boost::shared_ptr< ::tauv_joy::JoyConnectResponse > JoyConnectResponsePtr;
typedef boost::shared_ptr< ::tauv_joy::JoyConnectResponse const> JoyConnectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_joy::JoyConnectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_joy::JoyConnectResponse_<ContainerAllocator1> & lhs, const ::tauv_joy::JoyConnectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_joy::JoyConnectResponse_<ContainerAllocator1> & lhs, const ::tauv_joy::JoyConnectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_joy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::tauv_joy::JoyConnectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_joy/JoyConnectResponse";
  }

  static const char* value(const ::tauv_joy::JoyConnectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success   # indicate successful run of triggered service\n"
"string message # informational, e.g. for error messages\n"
;
  }

  static const char* value(const ::tauv_joy::JoyConnectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoyConnectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_joy::JoyConnectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_joy::JoyConnectResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_JOY_MESSAGE_JOYCONNECTRESPONSE_H
