// Generated by gencpp from file tauv_joy/JoyConnect.msg
// DO NOT EDIT!


#ifndef TAUV_JOY_MESSAGE_JOYCONNECT_H
#define TAUV_JOY_MESSAGE_JOYCONNECT_H

#include <ros/service_traits.h>


#include <tauv_joy/JoyConnectRequest.h>
#include <tauv_joy/JoyConnectResponse.h>


namespace tauv_joy
{

struct JoyConnect
{

typedef JoyConnectRequest Request;
typedef JoyConnectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JoyConnect
} // namespace tauv_joy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_joy::JoyConnect > {
  static const char* value()
  {
    return "4ac0afce82f389644128ac3ab46cf672";
  }

  static const char* value(const ::tauv_joy::JoyConnect&) { return value(); }
};

template<>
struct DataType< ::tauv_joy::JoyConnect > {
  static const char* value()
  {
    return "tauv_joy/JoyConnect";
  }

  static const char* value(const ::tauv_joy::JoyConnect&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_joy::JoyConnectRequest> should match
// service_traits::MD5Sum< ::tauv_joy::JoyConnect >
template<>
struct MD5Sum< ::tauv_joy::JoyConnectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_joy::JoyConnect >::value();
  }
  static const char* value(const ::tauv_joy::JoyConnectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_joy::JoyConnectRequest> should match
// service_traits::DataType< ::tauv_joy::JoyConnect >
template<>
struct DataType< ::tauv_joy::JoyConnectRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_joy::JoyConnect >::value();
  }
  static const char* value(const ::tauv_joy::JoyConnectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_joy::JoyConnectResponse> should match
// service_traits::MD5Sum< ::tauv_joy::JoyConnect >
template<>
struct MD5Sum< ::tauv_joy::JoyConnectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_joy::JoyConnect >::value();
  }
  static const char* value(const ::tauv_joy::JoyConnectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_joy::JoyConnectResponse> should match
// service_traits::DataType< ::tauv_joy::JoyConnect >
template<>
struct DataType< ::tauv_joy::JoyConnectResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_joy::JoyConnect >::value();
  }
  static const char* value(const ::tauv_joy::JoyConnectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_JOY_MESSAGE_JOYCONNECT_H
