// Generated by gencpp from file tauv_common/GetThrusterManagerConfig.msg
// DO NOT EDIT!


#ifndef TAUV_COMMON_MESSAGE_GETTHRUSTERMANAGERCONFIG_H
#define TAUV_COMMON_MESSAGE_GETTHRUSTERMANAGERCONFIG_H

#include <ros/service_traits.h>


#include <tauv_common/GetThrusterManagerConfigRequest.h>
#include <tauv_common/GetThrusterManagerConfigResponse.h>


namespace tauv_common
{

struct GetThrusterManagerConfig
{

typedef GetThrusterManagerConfigRequest Request;
typedef GetThrusterManagerConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetThrusterManagerConfig
} // namespace tauv_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_common::GetThrusterManagerConfig > {
  static const char* value()
  {
    return "b5a2d9d3bb510dd91fdb03f95e95b8de";
  }

  static const char* value(const ::tauv_common::GetThrusterManagerConfig&) { return value(); }
};

template<>
struct DataType< ::tauv_common::GetThrusterManagerConfig > {
  static const char* value()
  {
    return "tauv_common/GetThrusterManagerConfig";
  }

  static const char* value(const ::tauv_common::GetThrusterManagerConfig&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_common::GetThrusterManagerConfigRequest> should match
// service_traits::MD5Sum< ::tauv_common::GetThrusterManagerConfig >
template<>
struct MD5Sum< ::tauv_common::GetThrusterManagerConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::GetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterManagerConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::GetThrusterManagerConfigRequest> should match
// service_traits::DataType< ::tauv_common::GetThrusterManagerConfig >
template<>
struct DataType< ::tauv_common::GetThrusterManagerConfigRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_common::GetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterManagerConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_common::GetThrusterManagerConfigResponse> should match
// service_traits::MD5Sum< ::tauv_common::GetThrusterManagerConfig >
template<>
struct MD5Sum< ::tauv_common::GetThrusterManagerConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::GetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterManagerConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::GetThrusterManagerConfigResponse> should match
// service_traits::DataType< ::tauv_common::GetThrusterManagerConfig >
template<>
struct DataType< ::tauv_common::GetThrusterManagerConfigResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_common::GetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterManagerConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_COMMON_MESSAGE_GETTHRUSTERMANAGERCONFIG_H
