// Generated by gencpp from file tauv_common/GetThrusterCurve.msg
// DO NOT EDIT!


#ifndef TAUV_COMMON_MESSAGE_GETTHRUSTERCURVE_H
#define TAUV_COMMON_MESSAGE_GETTHRUSTERCURVE_H

#include <ros/service_traits.h>


#include <tauv_common/GetThrusterCurveRequest.h>
#include <tauv_common/GetThrusterCurveResponse.h>


namespace tauv_common
{

struct GetThrusterCurve
{

typedef GetThrusterCurveRequest Request;
typedef GetThrusterCurveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetThrusterCurve
} // namespace tauv_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_common::GetThrusterCurve > {
  static const char* value()
  {
    return "93e0d8a78977b3619bdc09f290ef57fa";
  }

  static const char* value(const ::tauv_common::GetThrusterCurve&) { return value(); }
};

template<>
struct DataType< ::tauv_common::GetThrusterCurve > {
  static const char* value()
  {
    return "tauv_common/GetThrusterCurve";
  }

  static const char* value(const ::tauv_common::GetThrusterCurve&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_common::GetThrusterCurveRequest> should match
// service_traits::MD5Sum< ::tauv_common::GetThrusterCurve >
template<>
struct MD5Sum< ::tauv_common::GetThrusterCurveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::GetThrusterCurve >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterCurveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::GetThrusterCurveRequest> should match
// service_traits::DataType< ::tauv_common::GetThrusterCurve >
template<>
struct DataType< ::tauv_common::GetThrusterCurveRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_common::GetThrusterCurve >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterCurveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_common::GetThrusterCurveResponse> should match
// service_traits::MD5Sum< ::tauv_common::GetThrusterCurve >
template<>
struct MD5Sum< ::tauv_common::GetThrusterCurveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::GetThrusterCurve >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterCurveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::GetThrusterCurveResponse> should match
// service_traits::DataType< ::tauv_common::GetThrusterCurve >
template<>
struct DataType< ::tauv_common::GetThrusterCurveResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_common::GetThrusterCurve >::value();
  }
  static const char* value(const ::tauv_common::GetThrusterCurveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_COMMON_MESSAGE_GETTHRUSTERCURVE_H
