// Generated by gencpp from file tauv_common/RegisterObjectDetections.msg
// DO NOT EDIT!


#ifndef TAUV_COMMON_MESSAGE_REGISTEROBJECTDETECTIONS_H
#define TAUV_COMMON_MESSAGE_REGISTEROBJECTDETECTIONS_H

#include <ros/service_traits.h>


#include <tauv_common/RegisterObjectDetectionsRequest.h>
#include <tauv_common/RegisterObjectDetectionsResponse.h>


namespace tauv_common
{

struct RegisterObjectDetections
{

typedef RegisterObjectDetectionsRequest Request;
typedef RegisterObjectDetectionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterObjectDetections
} // namespace tauv_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_common::RegisterObjectDetections > {
  static const char* value()
  {
    return "5cc8e5672e1e74a20b716902a91f95c7";
  }

  static const char* value(const ::tauv_common::RegisterObjectDetections&) { return value(); }
};

template<>
struct DataType< ::tauv_common::RegisterObjectDetections > {
  static const char* value()
  {
    return "tauv_common/RegisterObjectDetections";
  }

  static const char* value(const ::tauv_common::RegisterObjectDetections&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_common::RegisterObjectDetectionsRequest> should match
// service_traits::MD5Sum< ::tauv_common::RegisterObjectDetections >
template<>
struct MD5Sum< ::tauv_common::RegisterObjectDetectionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::RegisterObjectDetections >::value();
  }
  static const char* value(const ::tauv_common::RegisterObjectDetectionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::RegisterObjectDetectionsRequest> should match
// service_traits::DataType< ::tauv_common::RegisterObjectDetections >
template<>
struct DataType< ::tauv_common::RegisterObjectDetectionsRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_common::RegisterObjectDetections >::value();
  }
  static const char* value(const ::tauv_common::RegisterObjectDetectionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_common::RegisterObjectDetectionsResponse> should match
// service_traits::MD5Sum< ::tauv_common::RegisterObjectDetections >
template<>
struct MD5Sum< ::tauv_common::RegisterObjectDetectionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::RegisterObjectDetections >::value();
  }
  static const char* value(const ::tauv_common::RegisterObjectDetectionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::RegisterObjectDetectionsResponse> should match
// service_traits::DataType< ::tauv_common::RegisterObjectDetections >
template<>
struct DataType< ::tauv_common::RegisterObjectDetectionsResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_common::RegisterObjectDetections >::value();
  }
  static const char* value(const ::tauv_common::RegisterObjectDetectionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_COMMON_MESSAGE_REGISTEROBJECTDETECTIONS_H
