// Generated by gencpp from file tauv_common/RegisterMeasurement.msg
// DO NOT EDIT!


#ifndef TAUV_COMMON_MESSAGE_REGISTERMEASUREMENT_H
#define TAUV_COMMON_MESSAGE_REGISTERMEASUREMENT_H

#include <ros/service_traits.h>


#include <tauv_common/RegisterMeasurementRequest.h>
#include <tauv_common/RegisterMeasurementResponse.h>


namespace tauv_common
{

struct RegisterMeasurement
{

typedef RegisterMeasurementRequest Request;
typedef RegisterMeasurementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterMeasurement
} // namespace tauv_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_common::RegisterMeasurement > {
  static const char* value()
  {
    return "f2167c58c6c958d121ce25746a34db61";
  }

  static const char* value(const ::tauv_common::RegisterMeasurement&) { return value(); }
};

template<>
struct DataType< ::tauv_common::RegisterMeasurement > {
  static const char* value()
  {
    return "tauv_common/RegisterMeasurement";
  }

  static const char* value(const ::tauv_common::RegisterMeasurement&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_common::RegisterMeasurementRequest> should match
// service_traits::MD5Sum< ::tauv_common::RegisterMeasurement >
template<>
struct MD5Sum< ::tauv_common::RegisterMeasurementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::RegisterMeasurement >::value();
  }
  static const char* value(const ::tauv_common::RegisterMeasurementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::RegisterMeasurementRequest> should match
// service_traits::DataType< ::tauv_common::RegisterMeasurement >
template<>
struct DataType< ::tauv_common::RegisterMeasurementRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_common::RegisterMeasurement >::value();
  }
  static const char* value(const ::tauv_common::RegisterMeasurementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_common::RegisterMeasurementResponse> should match
// service_traits::MD5Sum< ::tauv_common::RegisterMeasurement >
template<>
struct MD5Sum< ::tauv_common::RegisterMeasurementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::RegisterMeasurement >::value();
  }
  static const char* value(const ::tauv_common::RegisterMeasurementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::RegisterMeasurementResponse> should match
// service_traits::DataType< ::tauv_common::RegisterMeasurement >
template<>
struct DataType< ::tauv_common::RegisterMeasurementResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_common::RegisterMeasurement >::value();
  }
  static const char* value(const ::tauv_common::RegisterMeasurementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_COMMON_MESSAGE_REGISTERMEASUREMENT_H
