// Generated by gencpp from file tauv_common/SetThrusterManagerConfig.msg
// DO NOT EDIT!


#ifndef TAUV_COMMON_MESSAGE_SETTHRUSTERMANAGERCONFIG_H
#define TAUV_COMMON_MESSAGE_SETTHRUSTERMANAGERCONFIG_H

#include <ros/service_traits.h>


#include <tauv_common/SetThrusterManagerConfigRequest.h>
#include <tauv_common/SetThrusterManagerConfigResponse.h>


namespace tauv_common
{

struct SetThrusterManagerConfig
{

typedef SetThrusterManagerConfigRequest Request;
typedef SetThrusterManagerConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetThrusterManagerConfig
} // namespace tauv_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_common::SetThrusterManagerConfig > {
  static const char* value()
  {
    return "e9f260f9f8a74cbd9cca6d6d276790c0";
  }

  static const char* value(const ::tauv_common::SetThrusterManagerConfig&) { return value(); }
};

template<>
struct DataType< ::tauv_common::SetThrusterManagerConfig > {
  static const char* value()
  {
    return "tauv_common/SetThrusterManagerConfig";
  }

  static const char* value(const ::tauv_common::SetThrusterManagerConfig&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_common::SetThrusterManagerConfigRequest> should match
// service_traits::MD5Sum< ::tauv_common::SetThrusterManagerConfig >
template<>
struct MD5Sum< ::tauv_common::SetThrusterManagerConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::SetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::SetThrusterManagerConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::SetThrusterManagerConfigRequest> should match
// service_traits::DataType< ::tauv_common::SetThrusterManagerConfig >
template<>
struct DataType< ::tauv_common::SetThrusterManagerConfigRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_common::SetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::SetThrusterManagerConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_common::SetThrusterManagerConfigResponse> should match
// service_traits::MD5Sum< ::tauv_common::SetThrusterManagerConfig >
template<>
struct MD5Sum< ::tauv_common::SetThrusterManagerConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_common::SetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::SetThrusterManagerConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_common::SetThrusterManagerConfigResponse> should match
// service_traits::DataType< ::tauv_common::SetThrusterManagerConfig >
template<>
struct DataType< ::tauv_common::SetThrusterManagerConfigResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_common::SetThrusterManagerConfig >::value();
  }
  static const char* value(const ::tauv_common::SetThrusterManagerConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_COMMON_MESSAGE_SETTHRUSTERMANAGERCONFIG_H
