(cl:defpackage tauv_msgs-msg
  (:use )
  (:export
   "<BUCKETDETECTION>"
   "BUCKETDETECTION"
   "<BUCKETLIST>"
   "BUCKETLIST"
   "<CONTROLLERCMD>"
   "CONTROLLERCMD"
   "<FLUIDDEPTH>"
   "FLUIDDEPTH"
   "<INERTIALVALS>"
   "INERTIALVALS"
   "<MPCREFTRAJ>"
   "MPCREFTRAJ"
   "<PIDVALS>"
   "PIDVALS"
   "<POSEGRAPHMEASUREMENT>"
   "POSEGRAPHMEASUREMENT"
   "<SONARPULSE>"
   "SONARPULSE"
  ))

